<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="ESLDellV3" name="ExaminationAndResultModule.SanityTest" tests="1" failures="0" timestamp="29 May 2018 11:03:59 GMT" time="11.243" errors="1">
  <testcase name="examinationResultSanityTest" time="11.243" classname="ExaminationAndResultModule.SanityTest">
    <error type="java.lang.IllegalArgumentException" message="Key Down / Up events only make sense for modifier keys.">
      <![CDATA[java.lang.IllegalArgumentException: Key Down / Up events only make sense for modifier keys.at org.openqa.selenium.interactions.internal.SingleKeyAction.<init>(SingleKeyAction.java:47)at org.openqa.selenium.interactions.internal.SingleKeyAction.<init>(SingleKeyAction.java:35)at org.openqa.selenium.interactions.KeyDownAction.<init>(KeyDownAction.java:41)at org.openqa.selenium.interactions.Actions.keyDown(Actions.java:118)at ExaminationAndResultModule.SanityTest.examinationResultSanityTest(SanityTest.java:58)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)]]>
    </error>
  </testcase> <!-- examinationResultSanityTest -->
</testsuite> <!-- ExaminationAndResultModule.SanityTest -->
